---
  - set_fact: package_name = httpd
    when: ansible_os_family == "Redhat"

  - set_fact: package_name = apache2
    when: ansible_os_family == "Debian"

  - name: install httpd (apache) package
    yum: name=httpd state=latest
    when: ansible_os_family == "Redhat"
    
  - name: install apache2 package
    when: ansible_os_family == "Debian"
